#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Oct 08, 2021 04:30:46 PM PDT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import UO_Linguistics_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    UO_Linguistics_support.set_Tk_var()
    top = Toplevel1 (root)
    UO_Linguistics_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    UO_Linguistics_support.set_Tk_var()
    top = Toplevel1 (w)
    UO_Linguistics_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x1080+0+-25")
        top.minsize(120, 120)
        top.maxsize(1920, 1080)
        top.resizable(1,  1)
        top.title("Eugene Science Center Speech Lab")
        top.configure(borderwidth="2")
        top.configure(background="#ffffff")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.005, rely=0.001, relheight=0.148
                , relwidth=0.407)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="4")
        self.Frame1.configure(background="#ffffff")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.017, rely=0.2, height=106, width=136)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#ffffff")
        photo_location = os.path.join(prog_location,"./Oval 1.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.214, rely=0.15, height=55, width=607)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(font="-family {DejaVu Sans} -size 36")
        self.Label2.configure(justify='left')
        self.Label2.configure(text='''CHOOSE A LANGUAGE''')

        self.Label2_1 = tk.Label(self.Frame1)
        self.Label2_1.place(relx=0.219, rely=0.531, height=54, width=478)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(background="#ffffff")
        self.Label2_1.configure(font="-family {DejaVu Sans} -size 36")
        self.Label2_1.configure(justify='left')
        self.Label2_1.configure(text='''ELIGE UN IDIOMA''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.408, rely=0.001, relheight=0.167
                , relwidth=0.591)
        self.Frame2.configure(relief='flat')
        self.Frame2.configure(borderwidth="4")
        self.Frame2.configure(background="#ffffff")

        self.Radiobutton1_1 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_1.place(relx=0.113, rely=0.078, relheight=0.417
                , relwidth=0.214)
        self.Radiobutton1_1.configure(activebackground="#f9f9f9")
        self.Radiobutton1_1.configure(command=UO_Linguistics_support.spanish)
        self.Radiobutton1_1.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton1_1.configure(indicatoron="0")
        self.Radiobutton1_1.configure(justify='left')
        self.Radiobutton1_1.configure(selectcolor="#f69900")
        self.Radiobutton1_1.configure(text='''Spanish''')
        self.Radiobutton1_1.configure(value=1)
        self.Radiobutton1_1.configure(variable=UO_Linguistics_support.selectedButton)

        self.Radiobutton1_2 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_2.place(relx=0.413, rely=0.078, relheight=0.406
                , relwidth=0.214)
        self.Radiobutton1_2.configure(activebackground="#f9f9f9")
        self.Radiobutton1_2.configure(command=UO_Linguistics_support.french)
        self.Radiobutton1_2.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton1_2.configure(indicatoron="0")
        self.Radiobutton1_2.configure(justify='left')
        self.Radiobutton1_2.configure(selectcolor="#f69900")
        self.Radiobutton1_2.configure(text='''French''')
        self.Radiobutton1_2.configure(value=2)
        self.Radiobutton1_2.configure(variable=UO_Linguistics_support.selectedButton)

        self.Radiobutton1_3 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_3.place(relx=0.713, rely=0.078, relheight=0.406
                , relwidth=0.214)
        self.Radiobutton1_3.configure(activebackground="#f9f9f9")
        self.Radiobutton1_3.configure(command=UO_Linguistics_support.mandarin)
        self.Radiobutton1_3.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton1_3.configure(indicatoron="0")
        self.Radiobutton1_3.configure(justify='left')
        self.Radiobutton1_3.configure(selectcolor="#f69900")
        self.Radiobutton1_3.configure(text='''Mandarin''')
        self.Radiobutton1_3.configure(value=3)
        self.Radiobutton1_3.configure(variable=UO_Linguistics_support.selectedButton)

        self.Radiobutton1_4 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_4.place(relx=0.115, rely=0.572, relheight=0.406
                , relwidth=0.212)
        self.Radiobutton1_4.configure(activebackground="#f9f9f9")
        self.Radiobutton1_4.configure(command=UO_Linguistics_support.japanese)
        self.Radiobutton1_4.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton1_4.configure(indicatoron="0")
        self.Radiobutton1_4.configure(justify='left')
        self.Radiobutton1_4.configure(selectcolor="#f69900")
        self.Radiobutton1_4.configure(text='''Japanese''')
        self.Radiobutton1_4.configure(value=4)
        self.Radiobutton1_4.configure(variable=UO_Linguistics_support.selectedButton)

        self.Radiobutton1_5 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_5.place(relx=0.414, rely=0.572, relheight=0.411
                , relwidth=0.214)
        self.Radiobutton1_5.configure(activebackground="#f9f9f9")
        self.Radiobutton1_5.configure(command=UO_Linguistics_support.ichishkiin)
        self.Radiobutton1_5.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton1_5.configure(indicatoron="0")
        self.Radiobutton1_5.configure(justify='left')
        self.Radiobutton1_5.configure(selectcolor="#f69900")
        self.Radiobutton1_5.configure(text='''Ichishkiin''')
        self.Radiobutton1_5.configure(value=5)
        self.Radiobutton1_5.configure(variable=UO_Linguistics_support.selectedButton)

        self.Radiobutton1_6 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_6.place(relx=0.713, rely=0.556, relheight=0.406
                , relwidth=0.214)
        self.Radiobutton1_6.configure(activebackground="#f9f9f9")
        self.Radiobutton1_6.configure(command=UO_Linguistics_support.english)
        self.Radiobutton1_6.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton1_6.configure(indicatoron="0")
        self.Radiobutton1_6.configure(justify='left')
        self.Radiobutton1_6.configure(selectcolor="#f69900")
        self.Radiobutton1_6.configure(text='''English''')
        self.Radiobutton1_6.configure(value=6)
        self.Radiobutton1_6.configure(variable=UO_Linguistics_support.selectedButton)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.005, rely=0.173, relheight=0.818
                , relwidth=0.243)
        self.Frame3.configure(relief='flat')
        self.Frame3.configure(borderwidth="1")
        self.Frame3.configure(background="#ffffff")

        self.Label1_1 = tk.Label(self.Frame3)
        self.Label1_1.place(relx=0.006, rely=0.024, height=107, width=136)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(background="#ffffff")
        photo_location = os.path.join(prog_location,"./Oval 2.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label1_1.configure(image=_img1)
        self.Label1_1.configure(text='''Label''')

        self.Label2_2 = tk.Label(self.Frame3)
        self.Label2_2.place(relx=0.279, rely=0.033, height=53, width=314)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(background="#ffffff")
        self.Label2_2.configure(font="-family {Segoe UI} -size 24")
        self.Label2_2.configure(justify='left')
        self.Label2_2.configure(text='''CHOOSE A PHRASE''')

        self.Label2_2_1 = tk.Label(self.Frame3)
        self.Label2_2_1.place(relx=0.288, rely=0.079, height=52, width=284)
        self.Label2_2_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1.configure(background="#ffffff")
        self.Label2_2_1.configure(font="-family {Segoe UI} -size 24")
        self.Label2_2_1.configure(justify='left')
        self.Label2_2_1.configure(text='''ELIGE UNA FRASE''')

        self.PButton1_1 = tk.Button(self.Frame3)
        self.PButton1_1.place(relx=0.039, rely=0.165, height=84, width=87)
        self.PButton1_1.configure(activebackground="#f9f9f9")
        self.PButton1_1.configure(command=UO_Linguistics_support.rp1)
        self.PButton1_1.configure(font="-family {DejaVu Sans} -size 12")
        self.PButton1_1.configure(pady="0")
        self.PButton1_1.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.PButton1_1.configure(wraplength="100")

        self.PButton1_2 = tk.Button(self.Frame3)
        self.PButton1_2.place(relx=0.041, rely=0.306, height=84, width=87)
        self.PButton1_2.configure(activebackground="#f9f9f9")
        self.PButton1_2.configure(command=UO_Linguistics_support.rp2)
        self.PButton1_2.configure(font="-family {DejaVu Sans} -size 12")
        self.PButton1_2.configure(padx="5")
        self.PButton1_2.configure(pady="0")
        self.PButton1_2.configure(text='''REVEAL PHRASE  REVELAR FRASE''')
        self.PButton1_2.configure(wraplength="100")

        self.PButton1_3 = tk.Button(self.Frame3)
        self.PButton1_3.place(relx=0.041, rely=0.447, height=84, width=87)
        self.PButton1_3.configure(activebackground="#f9f9f9")
        self.PButton1_3.configure(command=UO_Linguistics_support.rp3)
        self.PButton1_3.configure(font="-family {DejaVu Sans} -size 12")
        self.PButton1_3.configure(pady="0")
        self.PButton1_3.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.PButton1_3.configure(wraplength="100")

        self.PButton1_4 = tk.Button(self.Frame3)
        self.PButton1_4.place(relx=0.043, rely=0.588, height=84, width=87)
        self.PButton1_4.configure(activebackground="#f9f9f9")
        self.PButton1_4.configure(command=UO_Linguistics_support.rp4)
        self.PButton1_4.configure(font="-family {DejaVu Sans} -size 12")
        self.PButton1_4.configure(pady="0")
        self.PButton1_4.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.PButton1_4.configure(wraplength="100")

        self.PButton1_5 = tk.Button(self.Frame3)
        self.PButton1_5.place(relx=0.043, rely=0.728, height=84, width=87)
        self.PButton1_5.configure(activebackground="#f9f9f9")
        self.PButton1_5.configure(command=UO_Linguistics_support.rp5)
        self.PButton1_5.configure(font="-family {DejaVu Sans} -size 12")
        self.PButton1_5.configure(pady="0")
        self.PButton1_5.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.PButton1_5.configure(wraplength="100")

        self.PButton1_6 = tk.Button(self.Frame3)
        self.PButton1_6.place(relx=0.043, rely=0.864, height=84, width=87)
        self.PButton1_6.configure(activebackground="#f9f9f9")
        self.PButton1_6.configure(command=UO_Linguistics_support.rp6)
        self.PButton1_6.configure(font="-family {DejaVu Sans} -size 12")
        self.PButton1_6.configure(pady="0")
        self.PButton1_6.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.PButton1_6.configure(wraplength="100")

        self.Radiobutton2_1 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_1.place(relx=0.258, rely=0.159, relheight=0.1
                , relwidth=0.706)
        self.Radiobutton2_1.configure(activebackground="#f9f9f9")
        self.Radiobutton2_1.configure(background="#ffffff")
        self.Radiobutton2_1.configure(command=UO_Linguistics_support.ph1)
        self.Radiobutton2_1.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton2_1.configure(indicatoron="0")
        self.Radiobutton2_1.configure(justify='left')
        self.Radiobutton2_1.configure(offrelief="ridge")
        self.Radiobutton2_1.configure(selectcolor="#f69900")
        self.Radiobutton2_1.configure(text='''Phrase 1''')
        self.Radiobutton2_1.configure(value=21)
        self.Radiobutton2_1.configure(variable=UO_Linguistics_support.selectedPhrase)

        self.Radiobutton2_2 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_2.place(relx=0.258, rely=0.306, relheight=0.101
                , relwidth=0.704)
        self.Radiobutton2_2.configure(activebackground="#f9f9f9")
        self.Radiobutton2_2.configure(background="#ffffff")
        self.Radiobutton2_2.configure(command=UO_Linguistics_support.ph2)
        self.Radiobutton2_2.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton2_2.configure(indicatoron="0")
        self.Radiobutton2_2.configure(justify='left')
        self.Radiobutton2_2.configure(offrelief="ridge")
        self.Radiobutton2_2.configure(selectcolor="#f69900")
        self.Radiobutton2_2.configure(text='''Phrase 2''')
        self.Radiobutton2_2.configure(value=22)
        self.Radiobutton2_2.configure(variable=UO_Linguistics_support.selectedPhrase)

        self.Radiobutton2_3 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_3.place(relx=0.258, rely=0.447, relheight=0.1
                , relwidth=0.704)
        self.Radiobutton2_3.configure(activebackground="#f9f9f9")
        self.Radiobutton2_3.configure(background="#ffffff")
        self.Radiobutton2_3.configure(command=UO_Linguistics_support.ph3)
        self.Radiobutton2_3.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton2_3.configure(indicatoron="0")
        self.Radiobutton2_3.configure(justify='left')
        self.Radiobutton2_3.configure(offrelief="ridge")
        self.Radiobutton2_3.configure(selectcolor="#f69900")
        self.Radiobutton2_3.configure(text='''Phrase 3''')
        self.Radiobutton2_3.configure(value=23)
        self.Radiobutton2_3.configure(variable=UO_Linguistics_support.selectedPhrase)

        self.Radiobutton2_4 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_4.place(relx=0.258, rely=0.588, relheight=0.101
                , relwidth=0.704)
        self.Radiobutton2_4.configure(activebackground="#f9f9f9")
        self.Radiobutton2_4.configure(background="#ffffff")
        self.Radiobutton2_4.configure(command=UO_Linguistics_support.ph4)
        self.Radiobutton2_4.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton2_4.configure(indicatoron="0")
        self.Radiobutton2_4.configure(justify='left')
        self.Radiobutton2_4.configure(offrelief="ridge")
        self.Radiobutton2_4.configure(selectcolor="#f69900")
        self.Radiobutton2_4.configure(text='''Phrase 4''')
        self.Radiobutton2_4.configure(value=24)
        self.Radiobutton2_4.configure(variable=UO_Linguistics_support.selectedPhrase)

        self.Radiobutton2_5 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_5.place(relx=0.258, rely=0.725, relheight=0.102
                , relwidth=0.704)
        self.Radiobutton2_5.configure(activebackground="#f9f9f9")
        self.Radiobutton2_5.configure(background="#ffffff")
        self.Radiobutton2_5.configure(command=UO_Linguistics_support.ph5)
        self.Radiobutton2_5.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton2_5.configure(indicatoron="0")
        self.Radiobutton2_5.configure(justify='left')
        self.Radiobutton2_5.configure(offrelief="ridge")
        self.Radiobutton2_5.configure(selectcolor="#f69900")
        self.Radiobutton2_5.configure(text='''Phrase 5''')
        self.Radiobutton2_5.configure(value=25)
        self.Radiobutton2_5.configure(variable=UO_Linguistics_support.selectedPhrase)

        self.Radiobutton2_6 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6.place(relx=0.258, rely=0.861, relheight=0.101
                , relwidth=0.704)
        self.Radiobutton2_6.configure(activebackground="#f9f9f9")
        self.Radiobutton2_6.configure(background="#ffffff")
        self.Radiobutton2_6.configure(command=UO_Linguistics_support.ph6)
        self.Radiobutton2_6.configure(font="-family {Segoe UI} -size 24")
        self.Radiobutton2_6.configure(indicatoron="0")
        self.Radiobutton2_6.configure(justify='left')
        self.Radiobutton2_6.configure(offrelief="ridge")
        self.Radiobutton2_6.configure(selectcolor="#f69900")
        self.Radiobutton2_6.configure(text='''Phrase 6''')
        self.Radiobutton2_6.configure(value=26)
        self.Radiobutton2_6.configure(variable=UO_Linguistics_support.selectedPhrase)

        self.Label7 = tk.Label(self.Frame3)
        self.Label7.place(relx=0.987, rely=0.0, height=894, width=1)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(background="#0a0a0a")
        self.Label7.configure(text='''Label''')

        self.Frame4 = tk.Frame(top)
        self.Frame4.place(relx=0.251, rely=0.495, relheight=0.103
                , relwidth=0.743)
        self.Frame4.configure(relief='flat')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(background="#ffffff")

        self.Label3 = tk.Label(self.Frame4)
        self.Label3.place(relx=0.0, rely=-0.036, height=120, width=106)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#ffffff")
        photo_location = os.path.join(prog_location,"./Oval 3.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=_img2)
        self.Label3.configure(text='''Label''')

        self.Label2_2_2 = tk.Label(self.Frame4)
        self.Label2_2_2.place(relx=0.086, rely=0.0, height=50, width=696)
        self.Label2_2_2.configure(activebackground="#f9f9f9")
        self.Label2_2_2.configure(background="#ffffff")
        self.Label2_2_2.configure(font="-family {DejaVu Sans} -size 18")
        self.Label2_2_2.configure(justify='left')
        self.Label2_2_2.configure(text='''LISTEN TO THE PHRASE AND OBSERVE ITS WAVEFORM''')

        self.Label2_2_3 = tk.Label(self.Frame4)
        self.Label2_2_3.place(relx=0.077, rely=0.45, height=34, width=697)
        self.Label2_2_3.configure(activebackground="#f9f9f9")
        self.Label2_2_3.configure(background="#ffffff")
        self.Label2_2_3.configure(font="-family {DejaVu Sans} -size 18")
        self.Label2_2_3.configure(justify='left')
        self.Label2_2_3.configure(text='''ESCUCHA LA FRASE Y OBSERVA SU FORMA DE ONDA''')

        self.Button3_1 = tk.Button(self.Frame4)
        self.Button3_1.place(relx=0.619, rely=0.081, height=94, width=217)
        self.Button3_1.configure(activebackground="#f9f9f9")
        self.Button3_1.configure(anchor='w')
        self.Button3_1.configure(background="#ffffff")
        self.Button3_1.configure(command=UO_Linguistics_support.listen_phrase_button)
        self.Button3_1.configure(compound='right')
        self.Button3_1.configure(font="-family {DejaVu Sans} -size 14")
        photo_location = os.path.join(prog_location,"./Green Triangle-resized.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Button3_1.configure(image=_img3)
        self.Button3_1.configure(justify='left')
        self.Button3_1.configure(padx="10")
        self.Button3_1.configure(pady="0")
        self.Button3_1.configure(text='''REPLAY    REPETICIÓN''')
        self.Button3_1.configure(wraplength="160")

        self.Checkbutton1 = tk.Checkbutton(self.Frame4)
        self.Checkbutton1.place(relx=0.813, rely=0.072, relheight=0.865
                , relwidth=0.138)
        self.Checkbutton1.configure(activebackground="#f9f9f9")
        self.Checkbutton1.configure(background="#ffffff")
        self.Checkbutton1.configure(font="-family {Segoe UI} -size 13")
        self.Checkbutton1.configure(highlightbackground="#8000ff")
        self.Checkbutton1.configure(indicatoron="0")
        self.Checkbutton1.configure(offrelief="ridge")
        self.Checkbutton1.configure(selectcolor="#ff8000")
        self.Checkbutton1.configure(text='''Reduced Speed Velocidad Reducida''')
        self.Checkbutton1.configure(variable=UO_Linguistics_support.che45)
        self.Checkbutton1.configure(wraplength="200")

        self.Frame4_1 = tk.Frame(top)
        self.Frame4_1.place(relx=0.25, rely=0.885, relheight=0.106
                , relwidth=0.753)
        self.Frame4_1.configure(relief='flat')
        self.Frame4_1.configure(borderwidth="2")
        self.Frame4_1.configure(background="#ffffff")

        self.Label4 = tk.Label(self.Frame4_1)
        self.Label4.place(relx=0.084, rely=0.278, height=32, width=803)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(font="-family {DejaVu Sans} -size 17")
        self.Label4.configure(text='''TOUCH RECORD, SPEAK THE PHRASE AND OBSERVE ITS WAVEFORM''')

        self.Label5 = tk.Label(self.Frame4_1)
        self.Label5.place(relx=0.083, rely=0.609, height=31, width=831)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(font="-family {DejaVu Sans} -size 17")
        self.Label5.configure(text='''TOQUE GRABAR, HABLAR LA FRASE  Y OBSERVARLA FORMA DE ONDA''')

        self.Button2 = tk.Button(self.Frame4_1)
        self.Button2.place(relx=0.679, rely=0.191, height=94, width=167)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(anchor='w')
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(command=UO_Linguistics_support.record)
        self.Button2.configure(compound='right')
        self.Button2.configure(font="-family {Segoe UI} -size 14")
        photo_location = os.path.join(prog_location,"./Red Oval-resized.png")
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Button2.configure(image=_img4)
        self.Button2.configure(justify='left')
        self.Button2.configure(padx="10")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''RECORD     GRABAR''')
        self.Button2.configure(wraplength="80")

        self.Label6 = tk.Label(self.Frame4_1)
        self.Label6.place(relx=0.0, rely=0.078, height=109, width=108)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(background="#ffffff")
        photo_location = os.path.join(prog_location,"./Oval 4.png")
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.Label6.configure(image=_img5)
        self.Label6.configure(text='''Label''')

        self.Button3 = tk.Button(self.Frame4_1)
        self.Button3.place(relx=0.802, rely=0.174, height=94, width=217)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(anchor='w')
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(command=UO_Linguistics_support.play_recording)
        self.Button3.configure(compound='right')
        self.Button3.configure(font="-family {Segoe UI} -size 14")
        photo_location = os.path.join(prog_location,"./Green Triangle-resized.png")
        global _img6
        _img6 = tk.PhotoImage(file=photo_location)
        self.Button3.configure(image=_img6)
        self.Button3.configure(justify='left')
        self.Button3.configure(padx="10")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''REPLAY REPETICIÓN''')
        self.Button3.configure(wraplength="160")

        self.Frame5 = tk.Frame(top)
        self.Frame5.place(relx=0.25, rely=0.183, relheight=0.313, relwidth=0.747)

        self.Frame5.configure(relief='groove')
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief="groove")

        self.Frame6 = tk.Frame(top)
        self.Frame6.place(relx=0.25, rely=0.602, relheight=0.294, relwidth=0.746)

        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief="groove")

        self.Label8 = tk.Label(top)
        self.Label8.place(relx=0.01, rely=0.173, height=1, width=1888)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(background="#020202")
        self.Label8.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





