#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Oct 08, 2021 04:30:45 PM PDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    green_triangle_resized_png "./Green Triangle-resized.png" \
    oval_1_png "./Oval 1.png" \
    oval_2_png "./Oval 2.png" \
    oval_3_png "./Oval 3.png" \
    oval_4_(1)_png "./Oval 4 (1).png" \
    red_oval_resized_png "./Red Oval-resized.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 2 -background #ffffff -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1920x1080+0+-25
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1920 1080
    wm minsize $top 120 120
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Eugene Science Center Speech Lab"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 4 -background #ffffff -height 154 -highlightcolor black \
        -width 781 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image oval_1_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {DejaVu Sans} -size 36} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {CHOOSE A LANGUAGE} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {DejaVu Sans} -size 36} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ELIGE UN IDIOMA} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.201 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.662 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.214 -y 0 -rely 0.152 -width 0 \
        -relwidth 0.777 -height 0 -relheight 0.34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.219 -y 0 -rely 0.531 -width 0 \
        -relwidth 0.612 -height 0 -relheight 0.338 -anchor nw \
        -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 4 -background #ffffff -height 174 -highlightcolor black \
        -width 1135 
    vTcl:DefineAlias "$top.fra45" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    radiobutton $site_3_0.rad47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command spanish \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor #f69900 -text Spanish -value 1 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton1_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command french \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor #f69900 -text French -value 2 
    vTcl:DefineAlias "$site_3_0.rad45" "Radiobutton1_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command mandarin \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor #f69900 -text Mandarin -value 3 
    vTcl:DefineAlias "$site_3_0.rad46" "Radiobutton1_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command japanese \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor #f69900 -text Japanese -value 4 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton1_4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command ichishkiin \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor #f69900 -text Ichishkiin -value 5 
    vTcl:DefineAlias "$site_3_0.rad50" "Radiobutton1_5" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command english \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -selectcolor #f69900 -text English -value 6 
    vTcl:DefineAlias "$site_3_0.rad51" "Radiobutton1_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.113 -y 0 -rely 0.075 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.42 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.413 -y 0 -rely 0.075 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.408 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 0 -relx 0.713 -y 0 -rely 0.075 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.408 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.115 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.213 -height 0 -relheight 0.402 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 0 -relx 0.414 -y 0 -rely 0.575 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.408 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 0 -relx 0.713 -y 0 -rely 0.557 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.402 -anchor nw \
        -bordermode ignore 
    frame $top.fra52 \
        -borderwidth 1 -background #ffffff -highlightcolor black -width 466 
    vTcl:DefineAlias "$top.fra52" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image oval_2_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {CHOOSE A PHRASE} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ELIGE UNA FRASE} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_2_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command rp1 \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text {REVEAL PHRASE REVELAR FRASE} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but45" "PButton1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command rp2 \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 5 \
        -pady 0 -text {REVEAL PHRASE  REVELAR FRASE} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but46" "PButton1_2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command rp3 \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text {REVEAL PHRASE REVELAR FRASE} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but48" "PButton1_3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command rp4 \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text {REVEAL PHRASE REVELAR FRASE} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but49" "PButton1_4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command rp5 \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text {REVEAL PHRASE REVELAR FRASE} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but50" "PButton1_5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command rp6 \
        -font {-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text {REVEAL PHRASE REVELAR FRASE} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but51" "PButton1_6" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad53 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -command ph1 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -offrelief ridge -selectcolor #f69900 -text {Phrase 1} \
        -value 21 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad53" "Radiobutton2_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad45 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -command ph2 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -offrelief ridge -selectcolor #f69900 -text {Phrase 2} \
        -value 22 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad45" "Radiobutton2_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad46 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -command ph3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -offrelief ridge -selectcolor #f69900 -text {Phrase 3} \
        -value 23 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad46" "Radiobutton2_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad47 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -command ph4 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -offrelief ridge -selectcolor #f69900 -text {Phrase 4} \
        -value 24 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton2_4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -command ph5 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -offrelief ridge -selectcolor #f69900 -text {Phrase 5} \
        -value 25 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton2_5" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad49 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -command ph6 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -indicatoron 0 \
        -justify left -offrelief ridge -selectcolor #f69900 -text {Phrase 6} \
        -value 26 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad49" "Radiobutton2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #0a0a0a \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab45" "Label7" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.007 -y 0 -rely 0.024 -width 0 \
        -relwidth 0.292 -height 0 -relheight 0.121 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.279 -y 0 -rely 0.033 -width 0 \
        -relwidth 0.674 -height 0 -relheight 0.06 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.288 -y 0 -rely 0.079 -width 0 \
        -relwidth 0.609 -height 0 -relheight 0.059 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.165 -width 87 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.306 -width 87 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.04 -y 0 -rely 0.447 -width 87 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.588 -width 87 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.728 -width 87 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.864 -width 87 -relwidth 0 \
        -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad53 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.159 -width 0 \
        -relwidth 0.706 -height 0 -relheight 0.099 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.306 -width 0 \
        -relwidth 0.704 -height 0 -relheight 0.101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.704 -height 0 -relheight 0.1 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.588 -width 0 \
        -relwidth 0.704 -height 0 -relheight 0.1 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.725 -width 0 \
        -relwidth 0.704 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad49 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.861 -width 0 \
        -relwidth 0.704 -height 0 -relheight 0.101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.987 -y 0 -width 0 -relwidth 0.002 \
        -height 0 -relheight 1.012 -anchor nw -bordermode ignore 
    frame $top.fra57 \
        -borderwidth 2 -background #ffffff -height 107 -highlightcolor black \
        -width 1416 
    vTcl:DefineAlias "$top.fra57" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra57
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image oval_3_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab59" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {DejaVu Sans} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {LISTEN TO THE PHRASE AND OBSERVE ITS WAVEFORM} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label2_2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {DejaVu Sans} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ESCUCHA LA FRASE Y OBSERVA SU FORMA DE ONDA} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label2_2_3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #ffffff -command listen_phrase -compound right \
        -font {-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image green_triangle_resized_png -justify left -padx 10 -pady 0 \
        -text {REPLAY    REPETICIÓN} -wraplength 160 
    vTcl:DefineAlias "$site_3_0.but45" "Button3_1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che45 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #8000ff \
        -highlightcolor black -indicatoron 0 -offrelief ridge \
        -selectcolor #ff8000 -text {Reduced Speed Velocidad Reducida} \
        -variable che45 -wraplength 200 
    vTcl:DefineAlias "$site_3_0.che45" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -y 0 -rely -0.037 -width 0 -relwidth 0.074 \
        -height 0 -relheight 1.084 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.086 -y 0 -width 0 -relwidth 0.488 \
        -height 0 -relheight 0.45 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.077 -y 0 -rely 0.45 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.306 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.619 -y 0 -rely 0.081 -width 217 \
        -relwidth 0 -height 94 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che45 \
        -in $site_3_0 -x 0 -relx 0.813 -y 0 -rely 0.072 -width 0 \
        -relwidth 0.138 -height 0 -relheight 0.865 -anchor nw \
        -bordermode ignore 
    frame $top.fra58 \
        -borderwidth 2 -background #ffffff -height 110 -highlightcolor black \
        -width 1436 
    vTcl:DefineAlias "$top.fra58" "Frame4_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra58
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {DejaVu Sans} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {TOUCH RECORD, SPEAK THE PHRASE AND OBSERVE ITS WAVEFORM} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -font {-family {DejaVu Sans} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {TOQUE GRABAR, HABLAR LA FRASE  Y OBSERVARLA FORMA DE ONDA} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #ffffff -command record -compound right \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image red_oval_resized_png -justify left -padx 10 -pady 0 \
        -text {RECORD     GRABAR} -wraplength 80 
    vTcl:DefineAlias "$site_3_0.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image oval_4_(1)_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab51" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #ffffff -command play_recording -compound right \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image green_triangle_resized_png -justify left -padx 10 -pady 0 \
        -text {REPLAY REPETICIÓN} -wraplength 160 
    vTcl:DefineAlias "$site_3_0.but52" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.084 -y 0 -rely 0.278 -width 0 \
        -relwidth 0.555 -height 0 -relheight 0.278 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.083 -y 0 -rely 0.609 -width 0 \
        -relwidth 0.575 -height 0 -relheight 0.27 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.679 -y 0 -rely 0.191 -width 167 \
        -relwidth 0 -height 94 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -y 0 -rely 0.078 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.948 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.802 -y 0 -rely 0.174 -width 217 \
        -relwidth 0 -height 94 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 326 -highlightcolor black -width 1434 
    vTcl:DefineAlias "$top.fra47" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 300 -highlightcolor black -width 1433 
    vTcl:DefineAlias "$top.fra48" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #020202 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab48" "Label8" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.005 -y 0 -rely 0.001 -width 0 -relwidth 0.407 \
        -height 0 -relheight 0.148 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 0 -relx 0.408 -y 0 -rely 0.001 -width 0 -relwidth 0.591 \
        -height 0 -relheight 0.167 -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 0 -relx 0.005 -y 0 -rely 0.173 -width 0 -relwidth 0.243 \
        -height 0 -relheight 0.818 -anchor nw -bordermode ignore 
    place $top.fra57 \
        -in $top -x 0 -relx 0.251 -y 0 -rely 0.495 -width 0 -relwidth 0.743 \
        -height 0 -relheight 0.103 -anchor nw -bordermode ignore 
    place $top.fra58 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.885 -width 0 -relwidth 0.753 \
        -height 0 -relheight 0.107 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.183 -width 0 -relwidth 0.747 \
        -height 0 -relheight 0.313 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.602 -width 0 -relwidth 0.746 \
        -height 0 -relheight 0.294 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.173 -width 0 -relwidth 0.983 \
        -height 0 -relheight 0.001 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

