#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 23, 2022 11:12:51 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import weigh_page_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    weigh_page_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    weigh_page_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1920x1080")#+-13+0")
        #top.state('zoomed')
        #top.minsize(120, 1)
        #top.maxsize(3204, 1061)
        top.resizable(1,  1)
        top.title("Eugene Science Center Jump Station")
        top.configure(borderwidth="5")
        top.configure(background="#ff80c0")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.01, rely=0.254, relheight=0.484, relwidth=.49)#0.533)

        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(borderwidth="5")
        #self.Frame1.configure(relief="ridge")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.52, rely=0.254, relheight=0.484
                , relwidth=0.45)#0.444)
        self.Frame2.configure(relief='ridge')
        self.Frame2.configure(borderwidth="5")
        #self.Frame2.configure(relief="ridge")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.009, rely=0.02, height=128, width=817)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Arial Black} -size 32 -weight bold")
        self.Label1.configure(foreground="black")#"#0080ff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''How High Can You Jump?''')
        self.Label1.configure(wraplength="650")

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.012, rely=0.273, height=128, width=817)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#d9d9d9")
        self.Label2.configure(font="-family {Arial Black} -size 32 -weight bold")
        self.Label2.configure(foreground="black")#"#00bb00")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''How Long Can You Stay in the Air?''')
        self.Label2.configure(wraplength="650")

        self.Label3 = tk.Label(self.Frame2)
        self.Label3.place(relx=0.016, rely=0.508, height=128, width=812)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Arial Black} -size 32 -weight bold")
        self.Label3.configure(foreground="black")#"#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Stand on the Scale and Press the''')
        self.Label3.configure(wraplength="700")

        self.Label4 = tk.Label(self.Frame2)
        self.Label4.place(relx=0.016, rely=0.742, height=128, width=817)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Arial Black} -size 32 -weight bold")
        self.Label4.configure(foreground="black")#"#ff0000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''RED Button''')

if __name__ == '__main__':
    vp_start_gui()





