#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 24, 2021 07:50:40 PM PDT  platform: Windows NT
#    Jun 24, 2021 08:28:48 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def play_phrase():
    print('brad_support.play_phrase')
    sys.stdout.flush()

def rp1():
    print('brad_support.rp1')
    #sys.stdout.flush()
    dum="pl6"
    w.pl1.config(text="Phrase 1 Selected",bg="orange")
    w.pl2.config(text="Phrase 2",bg="white")
    w.pl3.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")
def rp2():
    print('brad_support.rp2')
    sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl2.config(text="Phrase 2 Selected",bg="orange")
    w.pl3.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp3():
    print('brad_support.rp3')
    sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl3.config(text="Phrase 3 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp4():
    print('brad_support.rp4')
    sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl4.config(text="Phrase 4 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl3.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp5():
    print('brad_support.rp5')
    sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl5.config(text="Phrase 5 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl3.config(text="Phrase 4",bg="white")
    w.pl4.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp6():
    print('brad_support.rp6')
    sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl6.config(text="Phrase 6 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl1.config(text="Phrase 6",bg="white")

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import brad
    brad.vp_start_gui()





