#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jun 01, 2021 09:28:59 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    green1_png "./green1.png" \
    green4_png "./green4.png" \
    greentriangle_png "./greentriangle.png" \
    image20 "./green2.png" \
    image21 "./green3.png" \
    redcircle_png "./redcircle.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1521x730+47+80
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2884 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -background #ffffff -height 141 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 443 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image green1_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {CHOOSE A LANGUAGE} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ELIGE UN IDIOMA} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.152 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.659 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.152 -width 0 \
        -relwidth 0.779 -height 0 -relheight 0.235 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.201 -y 0 -rely 0.53 -width 0 \
        -relwidth 0.752 -height 0 -relheight 0.235 -anchor nw \
        -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 2 -background #ffffff -height 142 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 789 
    vTcl:DefineAlias "$top.fra45" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    radiobutton $site_3_0.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Spanish \
        -value 1 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text French \
        -value 2 
    vTcl:DefineAlias "$site_3_0.rad45" "Radiobutton1_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Mandarin \
        -value 3 
    vTcl:DefineAlias "$site_3_0.rad46" "Radiobutton1_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Japanese \
        -value 4 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton1_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Ichishkiin \
        -value 5 
    vTcl:DefineAlias "$site_3_0.rad50" "Radiobutton1_3_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text English \
        -value 6 
    vTcl:DefineAlias "$site_3_0.rad51" "Radiobutton1_3_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.107 -y 0 -rely 0.072 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.36 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.403 -y 0 -rely 0.074 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 0 -relx 0.713 -y 0 -rely 0.074 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.109 -y 0 -rely 0.588 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 0 -relx 0.403 -y 0 -rely 0.588 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 0 -relx 0.713 -y 0 -rely 0.588 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    frame $top.fra52 \
        -borderwidth 2 -background #ffffff -height 635 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 358 
    vTcl:DefineAlias "$top.fra52" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image20 -text Label 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {CHOOSE A PHRASE} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ELIGE UNA FRASE} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_2_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -text {REVEAL PHRASE REVELAR FRASE} \
        -value 1 -variable phraseNum -wraplength 70 
    vTcl:DefineAlias "$site_3_0.rad63" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -text {REVEAL PHRASE REVELAR FRASE} \
        -value 2 -variable phraseNum -wraplength 70 
    vTcl:DefineAlias "$site_3_0.rad64" "Radiobutton2_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -text {REVEAL PHRASE REVELAR FRASE} \
        -value 3 -variable phraseNum -wraplength 70 
    vTcl:DefineAlias "$site_3_0.rad65" "Radiobutton2_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -text {REVEAL PHRASE REVELAR FRASE} \
        -value 6 -variable phraseNum -wraplength 70 
    vTcl:DefineAlias "$site_3_0.rad66" "Radiobutton2_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -text {REVEAL PHRASE REVELAR FRASE} \
        -value 5 -variable phraseNum -wraplength 70 
    vTcl:DefineAlias "$site_3_0.rad67" "Radiobutton2_4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -text {REVEAL PHRASE REVELAR FRASE} \
        -value 4 -variable phraseNum -wraplength 70 
    vTcl:DefineAlias "$site_3_0.rad68" "Radiobutton2_5" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief flat -relief ridge \
        -selectcolor #f69900 -text {Phrase 1} -value 1 -variable phraseNum 
    vTcl:DefineAlias "$site_3_0.rad69" "Radiobutton2_6" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief flat -relief ridge \
        -selectcolor #f69900 -text {Phrase 2} -value 2 -variable phraseNum 
    vTcl:DefineAlias "$site_3_0.rad70" "Radiobutton2_6_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief flat -relief ridge \
        -selectcolor #f69900 -text {Phrase 3} -value 3 -variable phraseNum 
    vTcl:DefineAlias "$site_3_0.rad71" "Radiobutton2_6_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief flat -relief ridge \
        -selectcolor #f69900 -text {Phrase 4} -value 4 -variable phraseNum 
    vTcl:DefineAlias "$site_3_0.rad72" "Radiobutton2_6_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief flat -relief ridge \
        -selectcolor #f69900 -text {Phrase 5} -value 5 -variable phraseNum 
    vTcl:DefineAlias "$site_3_0.rad73" "Radiobutton2_6_4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief flat -relief ridge \
        -selectcolor #f69900 -text {Phrase 6} -value 6 -variable phraseNum 
    vTcl:DefineAlias "$site_3_0.rad74" "Radiobutton2_6_5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.292 -height 0 \
        -relheight 0.142 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.295 -y 0 -rely 0.017 -width 0 \
        -relwidth 0.649 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.298 -y 0 -rely 0.085 -width 0 \
        -relwidth 0.646 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad63 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.171 -width 0 \
        -relwidth 0.258 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad64 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.307 -width 0 \
        -relwidth 0.258 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad65 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.258 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad66 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.853 -width 0 \
        -relwidth 0.258 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad67 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.717 -width 0 \
        -relwidth 0.258 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad68 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.58 -width 0 \
        -relwidth 0.258 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad69 \
        -in $site_3_0 -x 0 -relx 0.331 -y 0 -rely 0.171 -width 0 \
        -relwidth 0.656 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad70 \
        -in $site_3_0 -x 0 -relx 0.331 -y 0 -rely 0.307 -width 0 \
        -relwidth 0.656 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad71 \
        -in $site_3_0 -x 0 -relx 0.331 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.656 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad72 \
        -in $site_3_0 -x 0 -relx 0.331 -y 0 -rely 0.58 -width 0 \
        -relwidth 0.656 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad73 \
        -in $site_3_0 -x 0 -relx 0.331 -y 0 -rely 0.717 -width 0 \
        -relwidth 0.656 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad74 \
        -in $site_3_0 -x 0 -relx 0.335 -y 0 -rely 0.862 -width 0 \
        -relwidth 0.656 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    frame $top.fra57 \
        -borderwidth 2 -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 795 
    vTcl:DefineAlias "$top.fra57" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra57
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image21 -text Label 
    vTcl:DefineAlias "$site_3_0.lab59" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {LISTEN TO THE PHRASE AND OBSERVE ITS WAVEFORM} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label2_2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ESCUCHA L FRASE Y OBSERVA SU FORMA DE ONDA} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label2_2_3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -compound right -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image greentriangle_png -justify left -padx 0 -pady 0 \
        -text {REPLAY PREPETICION} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but45" "Button4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -y 0 -rely -0.132 -width 0 -relwidth 0.085 \
        -height 0 -relheight 1.079 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.086 -y 0 -width 0 -relwidth 0.503 \
        -height 0 -relheight 0.45 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.086 -y 0 -rely 0.5 -width 0 \
        -relwidth 0.491 -height 0 -relheight 0.313 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.605 -y 0 -rely 0.135 -width 177 \
        -relwidth 0 -height 54 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra58 \
        -borderwidth 2 -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 795 
    vTcl:DefineAlias "$top.fra58" "Frame4_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra58
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {TOUCH RECORD, SPEAK THE PHRASE AND OBSERVE ITS WAVEFORM} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {TOQUE GRABAR, HBLAR LA FRASE  Y OBSERVARLA FORMA DE ONDA} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -compound right -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image redcircle_png -justify left -pady 0 -text {RECORD     GRABAR} \
        -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image green4_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab51" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -compound right -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image greentriangle_png -justify left -padx 0 -pady 0 \
        -text {REPLAY PREPETICION} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but52" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.59 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.038 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.59 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.627 -y 0 -rely 0.11 -width 167 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx -0.011 -y 0 -width 0 -relwidth 0.088 \
        -height 0 -relheight 1.038 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.794 -y 0 -rely 0.13 -width 177 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    canvas $top.can45 \
        -background #80ffff -borderwidth 2 -closeenough 1.0 -height 232 \
        -highlightbackground #fdfce3 -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 920 
    vTcl:DefineAlias "$top.can45" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can46 \
        -background #80ffff -borderwidth 2 -closeenough 1.0 -height 220 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground blue \
        -selectforeground white -width 928 
    vTcl:DefineAlias "$top.can46" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -rely -0.008 -width 0 -relwidth 0.41 -height 0 \
        -relheight 0.196 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 0 -relx 0.383 -y 0 -rely -0.013 -width 0 -relwidth 0.616 \
        -height 0 -relheight 0.191 -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 0 -y 0 -rely 0.188 -width 0 -relwidth 0.28 -height 0 \
        -relheight 0.827 -anchor nw -bordermode ignore 
    place $top.fra57 \
        -in $top -x 0 -relx 0.281 -y 0 -rely 0.497 -width 0 -relwidth 0.728 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.fra58 \
        -in $top -x 0 -relx 0.275 -y 0 -rely 0.888 -width 0 -relwidth 0.728 \
        -height 0 -relheight 0.104 -anchor nw -bordermode ignore 
    place $top.can45 \
        -in $top -x 0 -relx 0.278 -y 0 -rely 0.181 -width 0 -relwidth 0.719 \
        -height 0 -relheight 0.312 -anchor nw -bordermode ignore 
    place $top.can46 \
        -in $top -x 0 -relx 0.275 -y 0 -rely 0.593 -width 0 -relwidth 0.725 \
        -height 0 -relheight 0.294 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

