#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 24, 2021 07:50:40 PM PDT  platform: Windows NT
#    Jun 24, 2021 08:28:48 PM PDT  platform: Windows NT
#    Jun 24, 2021 08:41:57 PM PDT  platform: Windows NT
#    Jun 24, 2021 08:44:25 PM PDT  platform: Windows NT
#    Jun 24, 2021 08:48:44 PM PDT  platform: Windows NT
#    Jun 24, 2021 08:52:43 PM PDT  platform: Windows NT

import sys
#import numpy as np
import tkinter as tk
#from tkinter import ttk
from scipy.io import wavfile
import sounddevice as sd
#from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg)
#from matplotlib.figure import Figure
import json
import sounddevice as sd
import re

''' if set to True, then no drag bars or window title
    useful for kiosk applications '''
nodragbars = False

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    
    w = gui
    top_level = top
    root = top
    # Use overrideredirect() method to remove all window drag bars and border
    if nodragbars:
        root.overrideredirect(True)

def play_phrase(data,samplerate):
    
    print('brad_support.play_phrase')
    #sys.stdout.flush()
    sd.play(data,samplerate) #normal playback speed

def display_phrase(wfile,canvas):
    global data,samplerate
    Canvas=canvas
    Canvas.delete("all")
    zoom = 1.2 #adjusts height of waveform to avoid clipping.
    samplerate, data = wavfile.read(wfile)
    length = data.shape[0] / samplerate
    
    x=Canvas.winfo_geometry() #get the size of the Canvas
    temp=re.findall(r'\d+',x) #parse it. 'r' is optional
    width = int(temp[0])
    height = int(temp[1])

    xval=0. #init x axis
    points=[] #create list of coordinates to plot
    
    yy=(data/height)* zoom #scale wave ampltude to height of Canvas widget times a zoom
    frac = width/len(data) #fractional index
    h2 = height/2
    for j in range(0,len(data)):#,len(data)//width):
        yval = (yy[j] + h2)  #add thsd.play(data,samplerate) #normal playback speede offset so all values are positive
        xval = xval + frac #add the fractional index (downsample)
        points.append(xval)
        points.append(yval) #now we have points of array x0,y0,x1,y1...
   
    Canvas.create_line(*points) #smoothing not necessary
    
    
def rp1():
    print('brad_support.rp1')
    #sys.stdout.flush() #needed?
    w.pl1.config(text="Phrase 1 Selected",bg="orange") 
    w.pl2.config(text="Phrase 2",bg="white")
    w.pl3.config(text="Phrase 3",bg="white") 
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")
    display_phrase('en\\English_1-10_intensity70.wav',w.Canvas1)
    
    
def rp2():
    print('brad_support.rp2')
    #sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl2.config(text="Phrase 2 Selected",bg="orange")
    w.pl3.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")
    #get the file name from the json array
    #for now, fix it for debugging
    display_phrase('example.wav',w.Canvas1)
    
   

def rp3():
    print('brad_support.rp3')
    #sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl3.config(text="Phrase 3 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp4():
    print('brad_support.rp4')
    #sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl4.config(text="Phrase 4 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl3.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp5():
    print('brad_support.rp5')
    #sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl5.config(text="Phrase 5 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl3.config(text="Phrase 4",bg="white")
    w.pl4.config(text="Phrase 5",bg="white")
    w.pl6.config(text="Phrase 6",bg="white")

def rp6():
    print('brad_support.rp6')
    #sys.stdout.flush()
    w.pl1.config(text="Phrase 1",bg="white")
    w.pl6.config(text="Phrase 6 Selected",bg="orange")
    w.pl2.config(text="Phrase 3",bg="white")
    w.pl4.config(text="Phrase 4",bg="white")
    w.pl5.config(text="Phrase 5",bg="white")
    w.pl1.config(text="Phrase 6",bg="white")

def listen_phrase():
    global data,samplerate
    print('brad_support.listen_phrase')
    sd.play(data,samplerate) #normal playback speed
    #sys.stdout.flush()

def play_recording():
    print('brad_support.play_recording')
    #sys.stdout.flush()

def record():
    print('brad_support.record')
    #sys.stdout.flush()
'''
def select_language():
    print('brad_support.select_language')
    #sys.stdout.flush()
'''
def english():
    print('brad_support.english')
    #sys.stdout.flush()

def french():
    print('brad_support.french')
    #sys.stdout.flush()

def ichishkiin():
    print('brad_support.ichishkiin')
    #sys.stdout.flush()

def japanese():
    print('brad_support.japanese')
    #sys.stdout.flush()

def mandaarin():
    print('brad_support.mandaarin')
    #sys.stdout.flush()

def spanish():
    print('brad_support.spanish')
    #sys.stdout.flush()

def mandarin():
    print('brad_support.mandarin')
    #sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import brad
    print("starting program")
    brad.vp_start_gui()
    print("finished...")





