#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 22, 2021 03:08:31 PM PDT  platform: Windows NT

import sys
#import ESC_Class as ESC
import tkinter as tk
from scipy.io import wavfile
import sounddevice as sd
import re
from time import perf_counter
from tkinter import ttk
from scipy.io import wavfile
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg)
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.figure import Figure
import time

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()
    global selectedPhrase
    selectedPhrase = tk.IntVar()

### Global Values ###
PHRASE =["1...2...3...4...5\n6...7...8...9...10", \
"Ducks are great!", \
"Have a nice day", \
"Hello", "How are you?", \
"My name is ...\nWhat is your name?"]

language = "English" #default

def init(top, gui, *args, **kwargs):
    global w, top_level, root
   
    w = gui
    top_level = top
    root = top

    global t
    t= True
    w.Radiobutton1_3_2.invoke() #start with English button enabled
    init_plot()
    
#hack for now until I can work out class library
def init_plot():
    global w
    global fig,plt,plt_canvas,f    
   
    f=ttk.Frame(w.Frame5)
   
    fig=Figure()
    plt = fig.add_subplot()
    fig.subplots_adjust(bottom=0.0, right=1.04, left=-.06, top=1.,wspace=0.0)
    plt_canvas = FigureCanvasTkAgg(fig, f)
    
    #plt.set_frame_on(False)
    #plt.get_xaxis().set_visible(False)
    #plt.get_yaxis().set_visible(False)
    
    print("init")

#hack for now until I have class written
def clear_plot():
    global w
    print('wave_plot_support.clear_plot')
    #sys.stdout.flush()
    for widget in w.Frame5.winfo_children():
        widget.destroy()
    init_plot()

def plot_phrase(wfile):
    
    global w,f,fig,plt,plt_canvas
    t0=perf_counter()
    clear_plot()
    #t0=perf_counter() #debug
    samplerate, data = wavfile.read(wfile)
    length = data.shape[0] / samplerate
    print(length) #debug
    f.pack(fill=tk.BOTH) #add figure
    
    plt_canvas._tkcanvas.pack(fill=tk.BOTH) #add canvas
    time=np.linspace(0.,(len(data)/samplerate),(len(data))) #x axis values

    plt.plot(time,data[:],linewidth=.4)
    t1=perf_counter() #debug
    print(t1-t0) #debug -- time it takes to plot
    
def english():
    print('brad_mpl_support.english')
    sys.stdout.flush()

def french():
    print('brad_mpl_support.french')
    sys.stdout.flush()

def ichishkiin():
    print('brad_mpl_support.ichishkiin')
    sys.stdout.flush()

def japanese():
    print('brad_mpl_support.japanese')
    sys.stdout.flush()

def listen_phrase():
    print('brad_mpl_support.listen_phrase')
    sys.stdout.flush()

def mandarin():
    print('brad_mpl_support.mandarin')
    sys.stdout.flush()

def ph1():
    print('brad_mpl_support.ph1')
    #clear_plot()
    plot_phrase("example.wav")    
    

def ph2():
    print('brad_mpl_support.ph2')
   
    #clear_plot()
    #time.sleep(1)
    plot_phrase("example1.wav")

def ph3():
    print('brad_mpl_support.ph3')
    sys.stdout.flush()

def ph4():
    print('brad_mpl_support.ph4')
    sys.stdout.flush()

def ph5():
    print('brad_mpl_support.ph5')
    sys.stdout.flush()

def ph6():
    print('brad_mpl_support.ph6')
    sys.stdout.flush()

def play_recording():
    print('brad_mpl_support.play_recording')
    sys.stdout.flush()

def record():
    print('brad_mpl_support.record')
    sys.stdout.flush()

def rp1():
    global t
    print('brad_mpl_support.rp1')
    sys.stdout.flush()
    if not t:
        w.Radiobutton2.config(text = "Phrase 1")
        t=True
    else:
        #w.Radiobutton2.config(fontsize="12")
        w.Radiobutton2.config(text=PHRASE[0])#'"1...2...3...4...5...\n6...7...8...9...10"')
        #One,Two,Three,Four,Five,\nSix,Seven,Eight,Nine,Ten")
        t=False

def rp2():
    print('brad_mpl_support.rp2')
    sys.stdout.flush()
    w.Radiobutton2_1.config(text=PHRASE[1])#'"Hello. My name is ...\nWhat is your name?"')

def rp3():
    print('brad_mpl_support.rp3')
    sys.stdout.flush()
    w.Radiobutton2_1_1.config(text=PHRASE[2])

def rp4():
    print('brad_mpl_support.rp4')
    sys.stdout.flush()
    w.Radiobutton2_1_2.config(text=PHRASE[3])

def rp5():
    print('brad_mpl_support.rp5')
    sys.stdout.flush()
    w.Radiobutton2_1_3.config(text=PHRASE[4])
    
def rp6():
    print('brad_mpl_support.rp6')
    sys.stdout.flush()
    w.Radiobutton2_1_4.config(text=PHRASE[5])

def spanish():
    print('brad_mpl_support.spanish')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import brad_mpl
    brad_mpl.vp_start_gui()





