#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jul 27, 2021 08:44:53 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    green1_png "./green1.png" \
    green4_png "./green4.png" \
    greentriangle_png "./greentriangle.png" \
    image20 "./green2.png" \
    image21 "./green3.png" \
    redcircle_png "./redcircle.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 2 -background #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1360x768+280+104
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2884 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Eugene Science Center Speech Lab"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 4 -relief ridge -background #ffffff -height 132 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 555 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image green1_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {CHOOSE A LANGUAGE} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ELIGE UN IDIOMA} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.151 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.658 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.213 -y 0 -rely 0.152 -width 0 \
        -relwidth 0.778 -height 0 -relheight 0.235 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.202 -y 0 -rely 0.53 -width 0 \
        -relwidth 0.752 -height 0 -relheight 0.235 -anchor nw \
        -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 4 -relief ridge -background #ffffff -height 136 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 709 
    vTcl:DefineAlias "$top.fra45" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    radiobutton $site_3_0.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command spanish \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Spanish \
        -value 1 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command french \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text French \
        -value 2 
    vTcl:DefineAlias "$site_3_0.rad45" "Radiobutton1_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command mandarin \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Mandarin \
        -value 3 
    vTcl:DefineAlias "$site_3_0.rad46" "Radiobutton1_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command japanese \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Japanese \
        -value 4 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton1_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command ichishkiin \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text Ichishkiin \
        -value 5 
    vTcl:DefineAlias "$site_3_0.rad50" "Radiobutton1_3_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command english \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -selectcolor #f69900 -text English \
        -value 6 
    vTcl:DefineAlias "$site_3_0.rad51" "Radiobutton1_3_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.113 -y 0 -rely 0.074 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.36 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.413 -y 0 -rely 0.074 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 0 -relx 0.713 -y 0 -rely 0.074 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.113 -y 0 -rely 0.588 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.346 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 0 -relx 0.413 -y 0 -rely 0.551 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.353 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 0 -relx 0.713 -y 0 -rely 0.555 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.349 -anchor nw \
        -bordermode ignore 
    frame $top.fra52 \
        -borderwidth 2 -background #ffffff -height 636 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 336 
    vTcl:DefineAlias "$top.fra52" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image20 -text Label 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {CHOOSE A PHRASE} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ELIGE UNA FRASE} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_2_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command rp1 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {REVEAL PHRASE REVELAR FRASE} -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but45" "PButton1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command rp2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {REVEAL PHRASE REVELAR FRASE} -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but46" "PButton1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command rp3 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {REVEAL PHRASE REVELAR FRASE} -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but48" "PButton1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command rp4 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {REVEAL PHRASE REVELAR FRASE} -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but49" "PButton1_1_2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command rp5 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {REVEAL PHRASE REVELAR FRASE} -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but50" "PButton1_1_3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command rp6 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {REVEAL PHRASE REVELAR FRASE} -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but51" "PButton1_1_4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command ph1 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief ridge -selectcolor #f69900 \
        -text {Phrase 1} -value 21 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad53" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command ph2 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief ridge -selectcolor #f69900 \
        -text {Phrase 2} -value 22 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad45" "Radiobutton2_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command ph3 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief ridge -selectcolor #f69900 \
        -text {Phrase 3} -value 23 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad46" "Radiobutton2_1_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command ph4 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief ridge -selectcolor #f69900 \
        -text {Phrase 4} -value 24 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton2_1_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command ph5 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief ridge -selectcolor #f69900 \
        -text {Phrase 5} -value 25 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton2_1_3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command ph6 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -indicatoron 0 -justify left -offrelief ridge -selectcolor #f69900 \
        -text {Phrase 6} -value 26 -variable selectedPhrase 
    vTcl:DefineAlias "$site_3_0.rad49" "Radiobutton2_1_4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.292 -height 0 \
        -relheight 0.142 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.295 -y 0 -rely 0.017 -width 0 \
        -relwidth 0.649 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.289 -y 0 -rely 0.063 -width 0 \
        -relwidth 0.646 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.142 -width 117 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.283 -width 117 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.425 -width 117 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.566 -width 117 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.708 -width 117 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.849 -width 117 \
        -relwidth 0 -height 84 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad53 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.142 -width 0 \
        -relwidth 0.625 -height 0 -relheight 0.134 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad45 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.283 -width 0 \
        -relwidth 0.625 -height 0 -relheight 0.135 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.425 -width 0 \
        -relwidth 0.625 -height 0 -relheight 0.135 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.566 -width 0 \
        -relwidth 0.625 -height 0 -relheight 0.135 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.708 -width 0 \
        -relwidth 0.625 -height 0 -relheight 0.135 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad49 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.849 -width 0 \
        -relwidth 0.625 -height 0 -relheight 0.135 -anchor nw \
        -bordermode ignore 
    frame $top.fra57 \
        -borderwidth 2 -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 795 
    vTcl:DefineAlias "$top.fra57" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra57
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image21 -text Label 
    vTcl:DefineAlias "$site_3_0.lab59" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {LISTEN TO THE PHRASE AND OBSERVE ITS WAVEFORM} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label2_2_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ESCUCHA L FRASE Y OBSERVA SU FORMA DE ONDA} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label2_2_3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command listen_phrase -compound right \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image greentriangle_png -justify left -padx 0 -pady 0 \
        -text {REPLAY PREPETICION} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but45" "Button3_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -y 0 -rely -0.127 -width 0 -relwidth 0.087 \
        -height 0 -relheight 1.076 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.086 -y 0 -width 0 -relwidth 0.503 \
        -height 0 -relheight 0.45 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.081 -y 0 -rely 0.506 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.304 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.61 -y 0 -rely 0.103 -width 177 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra58 \
        -borderwidth 2 -background #ffffff -height 80 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 980 
    vTcl:DefineAlias "$top.fra58" "Frame4_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra58
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {TOUCH RECORD, SPEAK THE PHRASE AND OBSERVE ITS WAVEFORM} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {TOQUE GRABAR, HBLAR LA FRASE  Y OBSERVARLA FORMA DE ONDA} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command record -compound right \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image redcircle_png -justify left -pady 0 -text {RECORD     GRABAR} \
        -wraplength 70 
    vTcl:DefineAlias "$site_3_0.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image green4_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab51" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -command play_recording -compound right \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image greentriangle_png -justify left -padx 0 -pady 0 \
        -text {REPLAY PREPETICION} -wraplength 100 
    vTcl:DefineAlias "$site_3_0.but52" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.084 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.533 -height 0 -relheight 0.275 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.077 -y 0 -rely 0.538 -width 0 \
        -relwidth 0.548 -height 0 -relheight 0.275 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.628 -y 0 -rely 0.163 -width 147 \
        -relwidth 0 -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.02 -y 0 -width 0 -relwidth 0.078 -height 0 \
        -relheight 1.038 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.808 -y 0 -rely 0.125 -width 157 \
        -relwidth 0 -height 54 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 235 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 967 
    vTcl:DefineAlias "$top.fra47" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 235 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 967 
    vTcl:DefineAlias "$top.fra48" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.007 -y 0 -rely 0.001 -width 0 -relwidth 0.407 \
        -height 0 -relheight 0.177 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 0 -relx 0.408 -y 0 -rely 0.001 -width 0 -relwidth 0.591 \
        -height 0 -relheight 0.177 -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 0 -y 0 -rely 0.182 -width 0 -relwidth 0.28 -height 0 \
        -relheight 0.828 -anchor nw -bordermode ignore 
    place $top.fra57 \
        -in $top -x 0 -relx 0.279 -y 0 -rely 0.495 -width 0 -relwidth 0.728 \
        -height 0 -relheight 0.103 -anchor nw -bordermode ignore 
    place $top.fra58 \
        -in $top -x 0 -relx 0.282 -y 0 -rely 0.888 -width 0 -relwidth 0.721 \
        -height 0 -relheight 0.104 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.287 -y 0 -rely 0.182 -width 0 -relwidth 0.711 \
        -height 0 -relheight 0.306 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.287 -y 0 -rely 0.599 -width 0 -relwidth 0.711 \
        -height 0 -relheight 0.306 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

