#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 22, 2021 03:06:29 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()
    global selectedPhrase
    selectedPhrase = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def english():
    print('brad-mpl_support.english')
    sys.stdout.flush()

def french():
    print('brad-mpl_support.french')
    sys.stdout.flush()

def ichishkiin():
    print('brad-mpl_support.ichishkiin')
    sys.stdout.flush()

def japanese():
    print('brad-mpl_support.japanese')
    sys.stdout.flush()

def listen_phrase():
    print('brad-mpl_support.listen_phrase')
    sys.stdout.flush()

def mandarin():
    print('brad-mpl_support.mandarin')
    sys.stdout.flush()

def ph1():
    print('brad-mpl_support.ph1')
    sys.stdout.flush()

def ph2():
    print('brad-mpl_support.ph2')
    sys.stdout.flush()

def ph3():
    print('brad-mpl_support.ph3')
    sys.stdout.flush()

def ph4():
    print('brad-mpl_support.ph4')
    sys.stdout.flush()

def ph5():
    print('brad-mpl_support.ph5')
    sys.stdout.flush()

def ph6():
    print('brad-mpl_support.ph6')
    sys.stdout.flush()

def play_recording():
    print('brad-mpl_support.play_recording')
    sys.stdout.flush()

def record():
    print('brad-mpl_support.record')
    sys.stdout.flush()

def rp1():
    print('brad-mpl_support.rp1')
    sys.stdout.flush()

def rp2():
    print('brad-mpl_support.rp2')
    sys.stdout.flush()

def rp3():
    print('brad-mpl_support.rp3')
    sys.stdout.flush()

def rp4():
    print('brad-mpl_support.rp4')
    sys.stdout.flush()

def rp5():
    print('brad-mpl_support.rp5')
    sys.stdout.flush()

def rp6():
    print('brad-mpl_support.rp6')
    sys.stdout.flush()

def spanish():
    print('brad-mpl_support.spanish')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import brad-mpl
    brad-mpl.vp_start_gui()




