#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 28, 2021 01:41:40 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import brad_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    brad_support.set_Tk_var()
    top = Toplevel1 (root)
    brad_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    brad_support.set_Tk_var()
    top = Toplevel1 (w)
    brad_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1080x720+404+37")
        top.minsize(120, 1)
        top.maxsize(2884, 881)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=-0.008, relheight=0.196, relwidth=0.41)
        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="ridge")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.023, rely=0.149, height=93, width=77)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../PAGE/green1.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.201, rely=0.149, height=34, width=345)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 24")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(justify='left')
        self.Label2.configure(text='''CHOOSE A LANGUAGE''')

        self.Label2_1 = tk.Label(self.Frame1)
        self.Label2_1.place(relx=0.201, rely=0.532, height=33, width=333)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#ffffff")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Segoe UI} -size 24")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(justify='left')
        self.Label2_1.configure(text='''ELIGE UN IDIOMA''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.404, rely=0.0, relheight=0.189, relwidth=0.593)
        self.Frame2.configure(relief='flat')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(background="#ffffff")
        self.Frame2.configure(cursor="fleur")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Radiobutton1 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1.place(relx=0.109, rely=0.074, relheight=0.36
                , relwidth=0.214)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(font="-family {Segoe UI} -size 16")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(indicatoron="0")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(selectcolor="#f69900")
        self.Radiobutton1.configure(text='''Spanish''')
        self.Radiobutton1.configure(value=1)
        self.Radiobutton1.configure(variable=brad_support.selectedButton)

        self.Radiobutton1_1 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_1.place(relx=0.403, rely=0.074, relheight=0.353
                , relwidth=0.214)
        self.Radiobutton1_1.configure(activebackground="#ececec")
        self.Radiobutton1_1.configure(activeforeground="#000000")
        self.Radiobutton1_1.configure(background="#d9d9d9")
        self.Radiobutton1_1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_1.configure(font="-family {Segoe UI} -size 16")
        self.Radiobutton1_1.configure(foreground="#000000")
        self.Radiobutton1_1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_1.configure(highlightcolor="black")
        self.Radiobutton1_1.configure(indicatoron="0")
        self.Radiobutton1_1.configure(justify='left')
        self.Radiobutton1_1.configure(selectcolor="#f69900")
        self.Radiobutton1_1.configure(text='''French''')
        self.Radiobutton1_1.configure(value=2)
        self.Radiobutton1_1.configure(variable=brad_support.selectedButton)

        self.Radiobutton1_2 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_2.place(relx=0.713, rely=0.074, relheight=0.353
                , relwidth=0.214)
        self.Radiobutton1_2.configure(activebackground="#ececec")
        self.Radiobutton1_2.configure(activeforeground="#000000")
        self.Radiobutton1_2.configure(background="#d9d9d9")
        self.Radiobutton1_2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_2.configure(font="-family {Segoe UI} -size 16")
        self.Radiobutton1_2.configure(foreground="#000000")
        self.Radiobutton1_2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_2.configure(highlightcolor="black")
        self.Radiobutton1_2.configure(indicatoron="0")
        self.Radiobutton1_2.configure(justify='left')
        self.Radiobutton1_2.configure(selectcolor="#f69900")
        self.Radiobutton1_2.configure(text='''Mandarin''')
        self.Radiobutton1_2.configure(value=3)
        self.Radiobutton1_2.configure(variable=brad_support.selectedButton)

        self.Radiobutton1_3 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_3.place(relx=0.109, rely=0.588, relheight=0.353
                , relwidth=0.214)
        self.Radiobutton1_3.configure(activebackground="#ececec")
        self.Radiobutton1_3.configure(activeforeground="#000000")
        self.Radiobutton1_3.configure(background="#d9d9d9")
        self.Radiobutton1_3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_3.configure(font="-family {Segoe UI} -size 16")
        self.Radiobutton1_3.configure(foreground="#000000")
        self.Radiobutton1_3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_3.configure(highlightcolor="black")
        self.Radiobutton1_3.configure(indicatoron="0")
        self.Radiobutton1_3.configure(justify='left')
        self.Radiobutton1_3.configure(selectcolor="#f69900")
        self.Radiobutton1_3.configure(text='''Japanese''')
        self.Radiobutton1_3.configure(value=4)
        self.Radiobutton1_3.configure(variable=brad_support.selectedButton)

        self.Radiobutton1_3_1 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_3_1.place(relx=0.403, rely=0.588, relheight=0.353
                , relwidth=0.214)
        self.Radiobutton1_3_1.configure(activebackground="#ececec")
        self.Radiobutton1_3_1.configure(activeforeground="#000000")
        self.Radiobutton1_3_1.configure(background="#d9d9d9")
        self.Radiobutton1_3_1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_3_1.configure(font="-family {Segoe UI} -size 16")
        self.Radiobutton1_3_1.configure(foreground="#000000")
        self.Radiobutton1_3_1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_3_1.configure(highlightcolor="black")
        self.Radiobutton1_3_1.configure(indicatoron="0")
        self.Radiobutton1_3_1.configure(justify='left')
        self.Radiobutton1_3_1.configure(selectcolor="#f69900")
        self.Radiobutton1_3_1.configure(text='''Ichishkiin''')
        self.Radiobutton1_3_1.configure(value=5)
        self.Radiobutton1_3_1.configure(variable=brad_support.selectedButton)

        self.Radiobutton1_3_2 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1_3_2.place(relx=0.713, rely=0.588, relheight=0.353
                , relwidth=0.214)
        self.Radiobutton1_3_2.configure(activebackground="#ececec")
        self.Radiobutton1_3_2.configure(activeforeground="#000000")
        self.Radiobutton1_3_2.configure(background="#d9d9d9")
        self.Radiobutton1_3_2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_3_2.configure(font="-family {Segoe UI} -size 16")
        self.Radiobutton1_3_2.configure(foreground="#000000")
        self.Radiobutton1_3_2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_3_2.configure(highlightcolor="black")
        self.Radiobutton1_3_2.configure(indicatoron="0")
        self.Radiobutton1_3_2.configure(justify='left')
        self.Radiobutton1_3_2.configure(selectcolor="#f69900")
        self.Radiobutton1_3_2.configure(text='''English''')
        self.Radiobutton1_3_2.configure(value=6)
        self.Radiobutton1_3_2.configure(variable=brad_support.selectedButton)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.0, rely=0.181, relheight=0.814, relwidth=0.28)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#ffffff")

        self.Label1_1 = tk.Label(self.Frame3)
        self.Label1_1.place(relx=0.0, rely=0.0, height=83, width=88)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c0c0c0")
        self.Label1_1.configure(cursor="fleur")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"./green2.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label1_1.configure(image=_img1)
        self.Label1_1.configure(text='''Label''')

        self.Label2_2 = tk.Label(self.Frame3)
        self.Label2_2.place(relx=0.295, rely=0.017, height=34, width=196)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#ffffff")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font="-family {Segoe UI} -size 14")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(justify='left')
        self.Label2_2.configure(text='''CHOOSE A PHRASE''')

        self.Label2_2_1 = tk.Label(self.Frame3)
        self.Label2_2_1.place(relx=0.298, rely=0.085, height=34, width=195)
        self.Label2_2_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1.configure(activeforeground="black")
        self.Label2_2_1.configure(background="#ffffff")
        self.Label2_2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1.configure(font="-family {Segoe UI} -size 14")
        self.Label2_2_1.configure(foreground="#000000")
        self.Label2_2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1.configure(highlightcolor="black")
        self.Label2_2_1.configure(justify='left')
        self.Label2_2_1.configure(text='''ELIGE UNA FRASE''')

        self.Radiobutton2 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2.place(relx=0.033, rely=0.171, relheight=0.111
                , relwidth=0.258)
        self.Radiobutton2.configure(activebackground="#ececec")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(indicatoron="0")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.Radiobutton2.configure(value=7)
        self.Radiobutton2.configure(variable=brad_support.selectedButton)
        self.Radiobutton2.configure(wraplength="70")

        self.Radiobutton2_1 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_1.place(relx=0.033, rely=0.307, relheight=0.111
                , relwidth=0.258)
        self.Radiobutton2_1.configure(activebackground="#ececec")
        self.Radiobutton2_1.configure(activeforeground="#000000")
        self.Radiobutton2_1.configure(background="#d9d9d9")
        self.Radiobutton2_1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_1.configure(foreground="#000000")
        self.Radiobutton2_1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_1.configure(highlightcolor="black")
        self.Radiobutton2_1.configure(indicatoron="0")
        self.Radiobutton2_1.configure(justify='left')
        self.Radiobutton2_1.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.Radiobutton2_1.configure(value=8)
        self.Radiobutton2_1.configure(variable=brad_support.selectedButton)
        self.Radiobutton2_1.configure(wraplength="70")

        self.Radiobutton2_2 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_2.place(relx=0.033, rely=0.444, relheight=0.111
                , relwidth=0.258)
        self.Radiobutton2_2.configure(activebackground="#ececec")
        self.Radiobutton2_2.configure(activeforeground="#000000")
        self.Radiobutton2_2.configure(background="#d9d9d9")
        self.Radiobutton2_2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_2.configure(foreground="#000000")
        self.Radiobutton2_2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_2.configure(highlightcolor="black")
        self.Radiobutton2_2.configure(indicatoron="0")
        self.Radiobutton2_2.configure(justify='left')
        self.Radiobutton2_2.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.Radiobutton2_2.configure(value=9)
        self.Radiobutton2_2.configure(variable=brad_support.selectedButton)
        self.Radiobutton2_2.configure(wraplength="70")

        self.Radiobutton2_3 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_3.place(relx=0.033, rely=0.853, relheight=0.111
                , relwidth=0.258)
        self.Radiobutton2_3.configure(activebackground="#ececec")
        self.Radiobutton2_3.configure(activeforeground="#000000")
        self.Radiobutton2_3.configure(background="#d9d9d9")
        self.Radiobutton2_3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_3.configure(foreground="#000000")
        self.Radiobutton2_3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_3.configure(highlightcolor="black")
        self.Radiobutton2_3.configure(indicatoron="0")
        self.Radiobutton2_3.configure(justify='left')
        self.Radiobutton2_3.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.Radiobutton2_3.configure(value=12)
        self.Radiobutton2_3.configure(variable=brad_support.selectedButton)
        self.Radiobutton2_3.configure(wraplength="70")

        self.Radiobutton2_4 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_4.place(relx=0.033, rely=0.717, relheight=0.111
                , relwidth=0.258)
        self.Radiobutton2_4.configure(activebackground="#ececec")
        self.Radiobutton2_4.configure(activeforeground="#000000")
        self.Radiobutton2_4.configure(background="#d9d9d9")
        self.Radiobutton2_4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_4.configure(foreground="#000000")
        self.Radiobutton2_4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_4.configure(highlightcolor="black")
        self.Radiobutton2_4.configure(indicatoron="0")
        self.Radiobutton2_4.configure(justify='left')
        self.Radiobutton2_4.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.Radiobutton2_4.configure(value=11)
        self.Radiobutton2_4.configure(variable=brad_support.selectedButton)
        self.Radiobutton2_4.configure(wraplength="70")

        self.Radiobutton2_5 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_5.place(relx=0.033, rely=0.58, relheight=0.111
                , relwidth=0.258)
        self.Radiobutton2_5.configure(activebackground="#ececec")
        self.Radiobutton2_5.configure(activeforeground="#000000")
        self.Radiobutton2_5.configure(background="#d9d9d9")
        self.Radiobutton2_5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_5.configure(foreground="#000000")
        self.Radiobutton2_5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_5.configure(highlightcolor="black")
        self.Radiobutton2_5.configure(indicatoron="0")
        self.Radiobutton2_5.configure(justify='left')
        self.Radiobutton2_5.configure(text='''REVEAL PHRASE REVELAR FRASE''')
        self.Radiobutton2_5.configure(value=10)
        self.Radiobutton2_5.configure(variable=brad_support.selectedButton)
        self.Radiobutton2_5.configure(wraplength="70")

        self.Radiobutton2_6 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6.place(relx=0.331, rely=0.171, relheight=0.111
                , relwidth=0.656)
        self.Radiobutton2_6.configure(activebackground="#ececec")
        self.Radiobutton2_6.configure(activeforeground="#000000")
        self.Radiobutton2_6.configure(background="#ffffff")
        self.Radiobutton2_6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_6.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2_6.configure(foreground="#000000")
        self.Radiobutton2_6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_6.configure(highlightcolor="black")
        self.Radiobutton2_6.configure(indicatoron="0")
        self.Radiobutton2_6.configure(justify='left')
        self.Radiobutton2_6.configure(offrelief="flat")
        self.Radiobutton2_6.configure(relief="ridge")
        self.Radiobutton2_6.configure(selectcolor="#f69900")
        self.Radiobutton2_6.configure(text='''Phrase 1''')
        self.Radiobutton2_6.configure(value=7)
        self.Radiobutton2_6.configure(variable=brad_support.selectedButton)

        self.Radiobutton2_6_1 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6_1.place(relx=0.331, rely=0.307, relheight=0.111
                , relwidth=0.656)
        self.Radiobutton2_6_1.configure(activebackground="#ececec")
        self.Radiobutton2_6_1.configure(activeforeground="#000000")
        self.Radiobutton2_6_1.configure(background="#ffffff")
        self.Radiobutton2_6_1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_6_1.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2_6_1.configure(foreground="#000000")
        self.Radiobutton2_6_1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_6_1.configure(highlightcolor="black")
        self.Radiobutton2_6_1.configure(indicatoron="0")
        self.Radiobutton2_6_1.configure(justify='left')
        self.Radiobutton2_6_1.configure(offrelief="flat")
        self.Radiobutton2_6_1.configure(relief="ridge")
        self.Radiobutton2_6_1.configure(selectcolor="#f69900")
        self.Radiobutton2_6_1.configure(text='''Phrase 2''')
        self.Radiobutton2_6_1.configure(value=8)
        self.Radiobutton2_6_1.configure(variable=brad_support.selectedButton)

        self.Radiobutton2_6_2 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6_2.place(relx=0.331, rely=0.444, relheight=0.111
                , relwidth=0.656)
        self.Radiobutton2_6_2.configure(activebackground="#ececec")
        self.Radiobutton2_6_2.configure(activeforeground="#000000")
        self.Radiobutton2_6_2.configure(background="#ffffff")
        self.Radiobutton2_6_2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_6_2.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2_6_2.configure(foreground="#000000")
        self.Radiobutton2_6_2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_6_2.configure(highlightcolor="black")
        self.Radiobutton2_6_2.configure(indicatoron="0")
        self.Radiobutton2_6_2.configure(justify='left')
        self.Radiobutton2_6_2.configure(offrelief="flat")
        self.Radiobutton2_6_2.configure(relief="ridge")
        self.Radiobutton2_6_2.configure(selectcolor="#f69900")
        self.Radiobutton2_6_2.configure(text='''Phrase 3''')
        self.Radiobutton2_6_2.configure(value=9)
        self.Radiobutton2_6_2.configure(variable=brad_support.selectedButton)

        self.Radiobutton2_6_3 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6_3.place(relx=0.331, rely=0.58, relheight=0.111
                , relwidth=0.656)
        self.Radiobutton2_6_3.configure(activebackground="#ececec")
        self.Radiobutton2_6_3.configure(activeforeground="#000000")
        self.Radiobutton2_6_3.configure(background="#ffffff")
        self.Radiobutton2_6_3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_6_3.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2_6_3.configure(foreground="#000000")
        self.Radiobutton2_6_3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_6_3.configure(highlightcolor="black")
        self.Radiobutton2_6_3.configure(indicatoron="0")
        self.Radiobutton2_6_3.configure(justify='left')
        self.Radiobutton2_6_3.configure(offrelief="flat")
        self.Radiobutton2_6_3.configure(relief="ridge")
        self.Radiobutton2_6_3.configure(selectcolor="#f69900")
        self.Radiobutton2_6_3.configure(text='''Phrase 4''')
        self.Radiobutton2_6_3.configure(value=10)
        self.Radiobutton2_6_3.configure(variable=brad_support.selectedButton)

        self.Radiobutton2_6_4 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6_4.place(relx=0.331, rely=0.717, relheight=0.111
                , relwidth=0.656)
        self.Radiobutton2_6_4.configure(activebackground="#ececec")
        self.Radiobutton2_6_4.configure(activeforeground="#000000")
        self.Radiobutton2_6_4.configure(background="#ffffff")
        self.Radiobutton2_6_4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_6_4.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2_6_4.configure(foreground="#000000")
        self.Radiobutton2_6_4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_6_4.configure(highlightcolor="black")
        self.Radiobutton2_6_4.configure(indicatoron="0")
        self.Radiobutton2_6_4.configure(justify='left')
        self.Radiobutton2_6_4.configure(offrelief="flat")
        self.Radiobutton2_6_4.configure(relief="ridge")
        self.Radiobutton2_6_4.configure(selectcolor="#f69900")
        self.Radiobutton2_6_4.configure(text='''Phrase 5''')
        self.Radiobutton2_6_4.configure(value=11)
        self.Radiobutton2_6_4.configure(variable=brad_support.selectedButton)

        self.Radiobutton2_6_5 = tk.Radiobutton(self.Frame3)
        self.Radiobutton2_6_5.place(relx=0.331, rely=0.853, relheight=0.111
                , relwidth=0.656)
        self.Radiobutton2_6_5.configure(activebackground="#ececec")
        self.Radiobutton2_6_5.configure(activeforeground="#000000")
        self.Radiobutton2_6_5.configure(background="#ffffff")
        self.Radiobutton2_6_5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2_6_5.configure(font="-family {Segoe UI} -size 18")
        self.Radiobutton2_6_5.configure(foreground="#000000")
        self.Radiobutton2_6_5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2_6_5.configure(highlightcolor="black")
        self.Radiobutton2_6_5.configure(indicatoron="0")
        self.Radiobutton2_6_5.configure(justify='left')
        self.Radiobutton2_6_5.configure(offrelief="flat")
        self.Radiobutton2_6_5.configure(relief="ridge")
        self.Radiobutton2_6_5.configure(selectcolor="#f69900")
        self.Radiobutton2_6_5.configure(text='''Phrase 6''')
        self.Radiobutton2_6_5.configure(value=12)
        self.Radiobutton2_6_5.configure(variable=brad_support.selectedButton)

        self.Frame4 = tk.Frame(top)
        self.Frame4.place(relx=0.278, rely=0.514, relheight=0.104
                , relwidth=0.728)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#ffffff")

        self.Label3 = tk.Label(self.Frame4)
        self.Label3.place(relx=0.0, rely=0.0, height=81, width=83)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        photo_location = os.path.join(prog_location,"./green3.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=_img2)
        self.Label3.configure(text='''Label''')

        self.Label2_2_2 = tk.Label(self.Frame4)
        self.Label2_2_2.place(relx=0.113, rely=0.0, height=34, width=345)
        self.Label2_2_2.configure(activebackground="#f9f9f9")
        self.Label2_2_2.configure(activeforeground="black")
        self.Label2_2_2.configure(background="#ffffff")
        self.Label2_2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2_2.configure(font="-family {Segoe UI} -size 10")
        self.Label2_2_2.configure(foreground="#000000")
        self.Label2_2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2_2.configure(highlightcolor="black")
        self.Label2_2_2.configure(justify='left')
        self.Label2_2_2.configure(text='''LISTEN TO THE PHRASE AND OBSERVE ITS WAVEFORM''')

        self.Label2_2_3 = tk.Label(self.Frame4)
        self.Label2_2_3.place(relx=0.113, rely=0.533, height=24, width=335)
        self.Label2_2_3.configure(activebackground="#f9f9f9")
        self.Label2_2_3.configure(activeforeground="black")
        self.Label2_2_3.configure(background="#ffffff")
        self.Label2_2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_2_3.configure(font="-family {Segoe UI} -size 10")
        self.Label2_2_3.configure(foreground="#000000")
        self.Label2_2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_2_3.configure(highlightcolor="black")
        self.Label2_2_3.configure(justify='left')
        self.Label2_2_3.configure(text='''ESCUCHA L FRASE Y OBSERVA SU FORMA DE ONDA''')

        self.Button1 = tk.Button(self.Frame4)
        self.Button1.place(relx=0.618, rely=0.133, height=54, width=117)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(justify='left')
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''REPLAY REPETICION''')
        self.Button1.configure(wraplength="70")

        self.Frame4_1 = tk.Frame(top)
        self.Frame4_1.place(relx=0.275, rely=0.889, relheight=0.104
                , relwidth=0.728)
        self.Frame4_1.configure(relief='groove')
        self.Frame4_1.configure(borderwidth="2")
        self.Frame4_1.configure(relief="groove")
        self.Frame4_1.configure(background="#d9d9d9")
        self.Frame4_1.configure(highlightbackground="#d9d9d9")
        self.Frame4_1.configure(highlightcolor="black")

if __name__ == '__main__':
    vp_start_gui()





